### ISSUE TITLE
Crash / Ticking block entity on older version

### ISSUE THREAD

**Issue by Ludi87** [SCLeoX/IntegratedNBT#2]
**Mods**:
Forge: 14.23.5.2854
CyclopsCore: 1.4.0        
CommonCapabilities: 2.4.2        
Integrated Dynamics: 1.0.15       
Integrated Dynamics Compat: 1.0.0        
Integrated NBT: 1.0          
JEI: 4.15.0.293   

Placed an NBT Extractor and a Variable Store next to it -> Instant crash
Tried after updating Cyclops Core, Common Capabilities and Integrated Dynamics to newest versions and it worked. So its obviously a problem with outdated versions.

I'd suggest to specify a minimum version somewhere (don't know if thats done in Curse or the Mod?), so people don't get confused with it.

[Crashlog](https://paste.dimdev.org/gizevalobi.mccrash)

**Comment by SCLeoX** [comment]
Hello again. I am not able to access your crashlog. Can you re-upload it? I think if I can see what is causing the issue, I can avoid having to manually test all versions to determine the minimal requirements.

**Comment by SCLeoX** [comment]
I was able to reproduce the issue myself. I picked a random version of Integrated Dynamics afterwards, which is v1.1.2, and it worked. So I am going to use that as the minimal requirements.

Anyways, thanks for letting me know. :)
