### ISSUE TITLE
Crash when removing Item from Inventory thats being used

### ISSUE THREAD

**Issue by Ludi87** [SCLeoX/IntegratedNBT#3]
Modpack: Infitech 3 with updated Commoncapabilities, Cyclopscore, Integrated Dynamics (all newest versions)

Steps:
- Put down Gregtech Battery Buffer, insert 4 full batteries
- Use block reader on Battery Buffer to get a Variable card with the NBT
- Get 4 Variable cards with the 4 Energy Levels of the batteries
- Addition of Variable 1+2 and 3+4 into new Variable cards
- Addition of the resulting cards into another new one
- Put variable cards in Variable storage, put result card into Display. Now the Total Energy is displayed.
- Remove one Battery from the Battery Buffer
- Crash

I tried to reproduce the crash only with Integrated Dynamics without the Addon, unfortunately I couldn't get it to work properly. Not sure if its not possible or if my knowledge is too limited.. (thats why I'm using the mod, it would make it a lot easier for me).

[Crashlog](https://paste.dimdev.org/feyihisuco.rb)

**Comment by SCLeoX** [comment]
Hello, thanks for reporting the crash. Unfortunately, I was not able to reproduce the crash with a similar setup (not with gregtech though).

I also cannot access your crash log (503 Service Unavailable). Can you try to re-upload it to another place?

Thanks.

**Comment by Ludi87** [comment]
https://pastebin.com/7wfWUJWy

**Comment by SCLeoX** [comment]
Fixed :)
