### ISSUE TITLE
Server crash when placing a variable received in nbt extractor operator mode into a display.

### ISSUE THREAD

**Issue by BLucky-gh** [SCLeoX/IntegratedNBT#5]
I got a static item->nbt()->nbt extractor in operator mode variable and placed it into a display panel or whatever it's called the server crashed. I'll try to get crashlogs from the server admin soon.

**Comment by BLucky-gh** [comment]
After some testing I got more data: the crash happens when I'm in the display panel GUI. the panel just shows NBT-> Any and when I try to open the UI to take the variable out it crashes the server. Breaking the panel seems to work fine.

**Comment by BLucky-gh** [comment]
Here are the crashlogs.

[crash-2020-12-06_10.25.17-server.txt](https://github.com/SCLeoX/IntegratedNBT/files/5649577/crash-2020-12-06_10.25.17-server.txt)
[crash-2020-12-06_10.33.16-server.txt](https://github.com/SCLeoX/IntegratedNBT/files/5649578/crash-2020-12-06_10.33.16-server.txt)

**Comment by SCLeoX** [comment]
It seems that the display panel is trying to print the type of the variable. However, since the type of the variable is a localized string and localization is only available on the client (because AFAIK server does not have a specific locale), the server crashed. I will try to reproduce it now.

**Comment by SCLeoX** [comment]
I have successfully reproduced the crash, and I have fixed this issue by switching to CyclopsCore's localization function for this use case. I will update the mod as soon as I figure out how to build the mod.

**Comment by SCLeoX** [comment]
The issue has been fixed. The updated mod has been uploaded to CurseForge. It is now waiting for review. Thank you for the report.

**Comment by BLucky-gh** [comment]
thanks for the quick fix
