### ISSUE TITLE
Please mark latest 1.16.4 file as 1.16.5 compatible

### ISSUE THREAD

**Issue by NillerMedDild** [SCLeoX/IntegratedNBT#7]
Pretty please :D It works just fine on 1.16.5, I need it marked as compatible to add it to my CurseForge instance.

**Comment by SCLeoX** [comment]
Done. And, thanks for testing it for me. [insert thumbs up emoji here]

**Comment by NillerMedDild** [comment]
Thanks! The thumbs up emoji is `:thumbsup:` fyi :P

**Comment by SCLeoX** [comment]
@NillerMedDild Not really. CurseForge just rejected my file because it says it is duplicated. I will try to insert some random txt file then.

**Comment by NillerMedDild** [comment]
Edit the existing one, check the 1.16.5 box :)

**Comment by SCLeoX** [comment]
@NillerMedDild Got it, thanks! :thumbsup:
