### ISSUE TITLE
[BUG] Blank NBT Extractor interface after inserting Villager NBT

### ISSUE THREAD

**Issue by met4000** [SCLeoX/IntegratedNBT#8]
Related Issue: https://github.com/CyclopsMC/IntegratedDynamics/issues/1003

I'm not sure if there is a more general underlying issue here, but this is the procedure that led to this specific problem;

1. Setup as described in [InDy#1003](https://github.com/CyclopsMC/IntegratedDynamics/issues/1003)
2. Use the NBT Extractor to extract `Offers.Recipes` (which is a list of NBT entries)
3. Take a `head` of the extracted recipe list
4. Insert the first extracted recipe (which is NBT data) into the NBT Extractor

![image](https://user-images.githubusercontent.com/15624876/110210881-bd58ac80-7ece-11eb-84e2-5c993c32e76c.png)

While testing this exact procedure to verify this was reproducible, it suddenly started working. However, relogging, inserting the Villager NBT card into the extractor, placing the Villager NBT card back into a display frame, and then inserting the head (extracted recipe) card back into the extractor seems to be a reliable way to cause it to not work. In the same line though, relogging with the head card still in the extractor, or placing it back into the extractor after relogging, seems to cause it to work again.

mod | version
--- | ---
MC | 1.16.4
InTu | 1.6.16
InTu Compat | 1.6.16
Cyclops Core | 1.11.1
Common Capabilities | 2.5.5
Forge | 35.1.4
InDy | 1.4.3
InDy Compat | 1.4.3
InNBT | 1.4.1
InCr | 1.0.11
InTerm | 1.1.1
InTerm Compat | 1.1.1
InREST | 1.1.2

**Comment by SCLeoX** [comment]
Thanks for reporting. I have failed to reproduce this in single player. I will try multiplayer now.

**Comment by SCLeoX** [comment]
Oh I know why.

NBT Extractors will remember the last scroll position. Therefore, you just need to scroll up.

I guess I will make it scroll to the top automatically when out of view.

**Comment by SCLeoX** [comment]
Done
