### ISSUE TITLE
[BUG] NBT Extractor does not cancel 'use item' when opened

### ISSUE THREAD

**Issue by met4000** [SCLeoX/IntegratedNBT#9]
'Activating' the NBT Extractor and causing the UI to popup by right-clicking ('use item'/'use'ing) it does not seem to correctly 'capture'/cancel the right-click/'use item' event; items that have a 'use' effect will trigger before the NBT Extractor UI triggers. This means that hand-held items that cause a UI to appear, such as InDy's Portable LP or Labeler, will have priority over the NBT Extractor's UI, and appear in place of it.

Other affects include (but of course are not limited to);
- Blocking with a shield while the UI is open
- Drawing/firing a bow while the UI is open
- Loading/firing a crossbow while the UI is open
- Throwing splash potions before the UI opens

Expected behaviour; the events mentioned above are cancelled/prevented from happening.
I don't know if that truly means cancelling the 'item use' event, or if that means that the NBT Extractor should be inheriting/implementing something that does that, but InDy and the vanilla source code should have examples that should be referenceable.

mod | version
--- | ---
MC | 1.16.4
Cyclops Core | 1.11.1
Common Capabilities | 2.5.5
Forge | 35.1.4
InNBT | 1.4.1

**Comment by SCLeoX** [comment]
Thanks for reporting. I have fixed this. I will close this issue as soon as the update is released.

**Comment by SCLeoX** [comment]
Done.
